name: gov-demo
recipe: drupal10
config:
  webroot: web
  xdebug: false
  composer_version: 2-latest
  php: 8.2
  database: mysql:8.0.34
  via: apache:2.4.53
services:
  appserver:
    build:
      - mkdir -p $LANDO_WEBROOT/sites/simpletest/browser_output
    run_as_root:
      - apt-get update
      - curl -sL https://deb.nodesource.com/setup_18.x | bash -
      - apt-get install -y nodejs
    port: 80
    overrides:
      environment:
        SIMPLETEST_BASE_URL: 'http://uscourts.local.dev'
        SIMPLETEST_DB: 'mysql://drupal10:drupal10@database/drupal10'
        MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", { "chromeOptions": { "args": [ "disable-gpu", "headless", "no-sandbox", "window-size=1200,700" ] } }, "http://chrome:4444"]'
        BROWSERTEST_OUTPUT_DIRECTORY: /app/web/sites/simpletest/browser_output
        SYMFONY_DEPRECATIONS_HELPER: 'disabled'
        VARNISH_PORT: 6081
        XDEBUG_MODE: debug,develop
  chrome:
    type: compose
    services:
      image: seleniarm/standalone-chromium:101
      command: /opt/bin/entry_point.sh
  mail:
    type: mailhog
    hogfrom:
      - appserver
tooling:
  varnish:
    service: varnish
    cmd: varnishd -a :6081 -f /etc/varnish/default.vcl
  phpunit:
    service: appserver
    description: Run PHPUnit tests including browser and javascript tests
    cmd: "phpunit -c /app/web/core/phpunit.xml.dist"
  robo:
    service: appserver
    description: Runs <robo> commmands
    cmd: /app/vendor/bin/robo
  behat:
    service: appserver
    cmd: vendor/bin/behat -c /app/tests/behat.yml
  npm:
    service: appserver
  npx:
    service: appserver
  node:
    service: appserver
  drush:
    cmd: /app/vendor/bin/drush
  drall:
    service: appserver
  xdebug-on:
    service: appserver
    description: Enable Xdebug.
    user: root
    cmd:
      - docker-php-ext-enable xdebug && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 2 && echo "Xdebug On" && tput sgr 0 && echo
  xdebug-off:
    service: appserver
    description: Disable Xdebug.
    user: root
    cmd:
      - rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 1 && echo "Xdebug Off" && tput sgr 0 && echo
env_file:
  - .lando.env
