<?php

/**
 * @file
 * Disable user 1.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function usc_user_1_user_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($entity->id() == 1) {
    return AccessResult::forbidden();
  }
  return AccessResult::neutral();
}
