_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  action: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  akamai: 0
  anchor_link: 0
  antibot: 0
  ape: 0
  auto_entitylabel: 0
  autologout: 0
  automated_cron: 0
  bean_migrate: 0
  bef_date_filters: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_visibility_groups: 0
  book: 0
  breakpoint: 0
  chosen: 0
  chosen_lib: 0
  ckeditor5: 0
  cl_editorial: 0
  conditional_fields: 0
  config: 0
  config_pages: 0
  config_split: 0
  content_moderation: 0
  contextual: 0
  customerror: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dropzonejs: 0
  dynamic_page_cache: 0
  editor: 0
  entity_extra_field: 0
  entity_extra_field_ui: 0
  entity_reference_revisions: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  event_log_track: 0
  event_log_track_auth: 0
  event_log_track_ui: 0
  extra_field: 0
  extra_field_plus: 0
  facets: 0
  facets_custom_order: 0
  facets_summary: 0
  faqfield: 0
  feeds: 0
  feeds_log: 0
  feeds_tamper: 0
  field: 0
  field_formatter_range: 0
  field_group: 0
  field_group_migrate: 0
  field_ui: 0
  field_validation: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  flood_control: 0
  fpa: 0
  geocoder: 0
  geofield: 0
  glossify: 0
  glossify_taxonomy: 0
  google_tag: 0
  google_translator: 0
  gutenberg: 0
  gutenberg_content_embed: 0
  gutenberg_uswds: 0
  gutenberg_uswds_accordion: 0
  gutenberg_uswds_alert: 0
  gutenberg_uswds_card: 0
  gutenberg_uswds_collection: 0
  gutenberg_uswds_gallery: 0
  gutenberg_uswds_icon: 0
  gutenberg_uswds_icon_list: 0
  gutenberg_uswds_intro_text: 0
  gutenberg_uswds_modal: 0
  gutenberg_uswds_process_list: 0
  gutenberg_uswds_summary_box: 0
  gutenberg_uswds_table: 0
  help: 0
  history: 0
  html_processors: 0
  htmlpurifier: 0
  iframe: 0
  image: 0
  image_link_formatter: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_autocomplete: 0
  jquery_ui_datepicker: 0
  jquery_ui_menu: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  legal: 0
  libraries: 0
  link: 0
  linkit: 0
  maxlength: 0
  media: 0
  media_library: 0
  media_library_edit: 0
  media_migration: 0
  media_migration_tools: 0
  menu_block: 0
  menu_breadcrumb: 0
  menu_item_extras: 0
  menu_link_content: 0
  menu_position: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  migmag: 0
  migmag_process: 0
  migrate: 0
  migrate_child_entity_generate: 0
  migrate_directory: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  migrate_manifest: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_source_html: 0
  migrate_tools: 0
  migrate_upgrade: 0
  moderated_content_bulk_publish: 0
  mysql: 0
  node: 0
  nomarkup: 0
  opa_file: 0
  options: 0
  page_cache: 0
  password_policy_character_types: 0
  password_policy_characters: 0
  password_policy_history: 0
  password_policy_length: 0
  path: 0
  path_alias: 0
  pathologic: 0
  phpass: 0
  piksel: 0
  purge: 0
  purge_tokens: 0
  purge_ui: 0
  quick_node_clone: 0
  readmore: 0
  redirect: 0
  redis: 0
  remote_stream_wrapper: 0
  responsive_image: 0
  robotstxt: 0
  role_hierarchy: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  sdc: 0
  sdc_display: 0
  sdc_tags: 0
  search: 0
  search_api: 0
  search_api_db: 0
  search_api_location: 0
  search_api_location_geocoder: 0
  search_api_location_views: 0
  search_autocomplete: 0
  seckit: 0
  serialization: 0
  shortcut: 0
  simple_media_bulk_upload: 0
  simple_sitemap: 0
  simple_sitemap_engines: 0
  single_content_sync: 0
  sitewide_alert: 0
  smart_sql_idmap: 0
  smart_trim: 0
  summary_only: 0
  svg_formatter: 0
  syslog: 0
  system: 0
  tamper: 0
  taxonomy: 0
  taxonomy_manager: 0
  taxonomy_parent_autocomplete: 0
  term_condition: 0
  text: 0
  token: 0
  token_views_filter: 0
  toolbar: 0
  transliterate_filenames: 0
  twig_tweak: 0
  usc_content_sync: 0
  usc_core: 0
  usc_court_finder: 0
  usc_failtest: 0
  usc_galleries: 0
  usc_liveness: 0
  usc_migrate_adjustments: 0
  usc_migrate_boolean: 0
  usc_migrate_gutenberg: 0
  usc_migrate_list: 0
  usc_search: 0
  usc_sitemap: 0
  usc_vacancies: 0
  user: 0
  usfedgov_google_analytics: 0
  varnish_purge_tags: 0
  varnish_purge_tags_override: 0
  varnish_purger: 0
  views_arg_entity_field: 0
  views_bulk_operations: 0
  views_filters_populate: 0
  views_ui: 0
  views_year_filter: 0
  viewsreference: 0
  wbm2cm: 0
  webform: 0
  webform_ui: 0
  workbench: 0
  workbench_access: 0
  workflows: 0
  extlink: 1
  pathauto: 1
  password_policy: 10
  views: 10
  paragraphs: 11
  tvi: 15
  minimal: 1000
theme:
  claro: 0
  uscgov: 0
  uscadmin: 0
profile: minimal
