_core:
  default_config_hash: mTDsmPALEAuqHvb9yCBNY05ZfE8IuZ4PFri2vxCw9qM
google_translator_active_languages_display_mode: SIMPLE
google_translator_active_languages:
  - af
  - sq
  - am
  - ar
  - hy
  - az
  - eu
  - be
  - bn
  - bs
  - bg
  - ca
  - ny
  - zh-CN
  - zh-TW
  - co
  - hr
  - cs
  - da
  - nl
  - en
  - eo
  - et
  - ee
  - tl
  - fi
  - fr
  - fy
  - gl
  - ka
  - de
  - el
  - gn
  - gu
  - ht
  - ha
  - haw
  - iw
  - hi
  - hu
  - is
  - ig
  - id
  - ga
  - it
  - ja
  - jw
  - kn
  - kk
  - km
  - rw
  - ko
  - kri
  - ku
  - ckb
  - ky
  - lo
  - lv
  - ln
  - lt
  - lg
  - mk
  - mg
  - ms
  - ml
  - mt
  - mi
  - mr
  - mn
  - ne
  - 'no'
  - or
  - om
  - ps
  - fa
  - pl
  - pt
  - pa
  - qu
  - ro
  - ru
  - gd
  - sr
  - st
  - sn
  - sd
  - si
  - sk
  - sl
  - so
  - es
  - su
  - sw
  - sv
  - tg
  - ta
  - tt
  - te
  - th
  - ti
  - tr
  - tk
  - ug
  - uk
  - ur
  - uz
  - vi
  - cy
  - xh
  - yi
  - yo
  - zu
google_translator_disclaimer_title: 'Automatic translation disclaimer'
google_translator_disclaimer: 'Translation of this page is provided by the third-party Google Translate service. In case of dispute, the original language content should prevail.'
