_core:
  default_config_hash: denrqScJlMiBdsks_UljTePRT-AAq-8PPlSluUFaxUs
registration_terms_style: 3
registration_container: 0
login_terms_style: 2
login_container: 0
user_profile_display: true
accept_every_login: false
except_roles: {  }
registration_modal_terms: true
login_modal_terms: true
