services:
  php:
    image: tugboatqa/php:8.2-apache

    default: true

    urls:
      # Homepage
      - url: /
        visualdiff:
          threshold: 90
      # Gov delivery form
      - url: /govdelivery-yo
        visualdiff:
          threshold: 90
      # Book
      - url: /default-content-book
        visualdiff:
          threshold: 90
      # Cameras in court with label-pill, intro text, table of contents, related news
      - url: /default-content-cameras-court-program
        visualdiff:
          threshold: 90
      # Court content type
      - url: /default-content-court
        visualdiff:
          threshold: 90
      # Data table content type with download-button, label-pill, side nav
      - url: /table-11-delayed-notice-search-warrant-civil-justice-reform-act-cjra-march-31-2024
        visualdiff:
          threshold: 90
      # Educational activity with Lead gallery, intro text, gallery
      - url: /default-content-educational-activity
        visualdiff:
          threshold: 80
      # FAQ (but currently without any FAQs)
      - url: /default-content-faqs
        visualdiff:
          threshold: 90
      # Federal probation journal with label-pill, and download button
      - url: /default-content-federal-probation-journal
        visualdiff:
          threshold: 90
      # Federal Rules with label-pill, and download button
      - url: /default-content-federal-rules
        visualdiff:
          threshold: 90
      # Fee with intro text, label pill, and published on
      - url: /default-content-fee
        visualdiff:
          threshold: 90
      # Form with label pill, download button
      - url: /default-content-form
        visualdiff:
          threshold: 90
      # Judge Comments with label pill, download button
      - url: /default-content-judge-comments
        visualdiff:
          threshold: 90
      # Judge content type
      - url: /default-content-judge
        visualdiff:
          threshold: 90
      # Gutenberg blocks: alert (normal, error), card (regular), icon list,
      # intro text, table, summary box, button
      - url: /gutenberg-blocks
        visualdiff:
          threshold: 90
      # Table of contents, gov delivery form, related news
      - url: /test-toc-news
        visualdiff:
          threshold: 90
      # In page navigation
      - url: /testing-page-navigation
        visualdiff:
          threshold: 90
      # News item with notification, lead image, lead gallery, audio, prose,
      # lists, graphic, related downloads, related links, latest content, gov
      # delivery, side nav.
      - url: /test/news/2024/06/05/visual-regression-test-news
        visualdiff:
          threshold: 80
      # FAQ with FAQs
      - url: /test/visual-regression-test-faq
        visualdiff:
          threshold: 90
      # Individual court
      - url: /federal-court-finder/location/59
        visualdiff:
          threshold: 90
      - url: /news/2012/04/20/losses-courts-underscore-funding-needs
        visualdiff:
          threshold: 90
      - url: /educational-resources/educational-activities/background-mendez-v-westminster-re-enactment
        visualdiff:
          threshold: 90
      - url: /brown-v-board-education-podcast
        visualdiff:
          threshold: 90



    # Wait until the mysql service is done building
    depends: mysql

    # A set of commands to run while building this service
    commands:
      # Commands that set up the basic preview infrastructure
      init:
        # Install and enable php-redis extension
        - wget https://github.com/FriendsOfPHP/pickle/releases/latest/download/pickle.phar -P /usr/bin
        - chmod +x /usr/bin/pickle.phar
        - pickle.phar install redis
        - docker-php-ext-enable redis

        # Install opcache and mod-rewrite.
        - docker-php-ext-install opcache
        - a2enmod headers rewrite

        # Link the document root to the expected path. This example links /web
        # to the docroot.
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"

        # Create the Drupal private files and config directories if they aren't
        # already present.
        - mkdir -p "${TUGBOAT_ROOT}/files-private"

        # Increase the php memory limit to 512MB.
        - echo "memory_limit = 512M" >> /usr/local/etc/php/conf.d/tugboat.ini
        - echo "max_input_vars = 6000" >> /usr/local/etc/php/conf.d/tugboat.ini
        # Install node.
        - apt-get update
        - apt-get install -yq ca-certificates curl gnupg
        - mkdir -p /etc/apt/keyrings
        - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
        - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
        - apt-get update
        - apt-get install -yq nodejs
        # Install zip library.
        - apt-get install libzip-dev
        - docker-php-ext-install zip

        # Use the tugboat-specific Drupal settings.
        - rm -rf "${DOCROOT}/sites/default/settings.db.php"
        - cp "${TUGBOAT_ROOT}/.tugboat/settings.local.php" "${DOCROOT}/sites/default/settings.db.php"

      # Commands that import files, databases,  or other assets. When an
      # existing preview is refreshed, the build workflow starts here,
      # skipping the init step, because the results of that step will
      # already be present.
      update:
        # Set file permissions such that Drupal will not complain
        - chgrp -R www-data "${DOCROOT}/sites"
        - find "${DOCROOT}/sites" -type d -exec chmod 2775 {} \;
        - find "${DOCROOT}/sites" -type f -exec chmod 0664 {} \;

      build:
        # Install/update packages managed by composer, including drush.
        - composer install --optimize-autoloader
        # Use the tugboat-specific Drupal settings.
        - rm -rf "${DOCROOT}/sites/default/settings.db.php"
        - cp "${TUGBOAT_ROOT}/.tugboat/settings.local.php" "${DOCROOT}/sites/default/settings.db.php"
        - vendor/bin/drush deploy -vvv
        # Import Default content.
        - vendor/bin/drush content:import ../content_default/test
        - vendor/bin/drush content:import ../content_default/prod
        # Compile theme.
        - cd web/themes/custom/uscgov/ && npm install && npx gulp init
        - vendor/bin/drush user:password agileana "${TESTADMIN_PASS}"
        - vendor/bin/drush cr

  # This 'mysql' key acts as the hostname to access the service by from the php service.
  mysql:
    image: tugboatqa/mysql:8.0

    # A set of commands to run while building this service
    commands:
      # Configure the server for the site to run on.
      init:
        # Increase the allowed packet size to 512MB.
        - mysql -e "SET GLOBAL max_allowed_packet=536870912;"
        # Ensure this packet size persists even if MySQL restarts.
        - echo "max_allowed_packet=536870912" >> /etc/mysql/conf.d/tugboat.cnf

      # Commands that import files, databases,  or other assets. When an
      # existing preview is refreshed, the build workflow starts here,
      # skipping the init step, because the results of that step will
      # already be present.
      update:
        - scp agileana@170.187.136.164:dbs_tugboat/uscgov.sql.gz /tmp/database.sql.gz
        - zcat /tmp/database.sql.gz | mysql tugboat
        - rm /tmp/database.sql.gz

  redis:
    image: tugboatqa/redis:6.2
