/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
"use strict";

(function (Drupal) {
  Drupal.behaviors.splideGallery = {
    attach: function attach(context) {
      context.querySelectorAll('.usc-gallery:not(.gallery-processed)').forEach(function (galleryField) {
        var mainSlider = new Splide(galleryField.querySelector('.main-slider'), {
          perPage: 2,
          gap: '1.5rem',
          arrows: true,
          padding: {
            left: 0,
            right: '10%'
          },
          breakpoints: {
            1400: {
              perPage: 2
            },
            800: {
              perPage: 1
            }
          }
        });
        mainSlider.mount(window.splide.Extensions);
        var lightbox = GLightbox({});
        galleryField.querySelectorAll('.main-slider .splide__slide__container a').forEach(function (image) {
          image.addEventListener('click', function (e) {
            var item_number = 0;
            e.preventDefault();
            var slider = this.closest(".splide__list");
            var slideritems = [];
            slider.querySelectorAll('.splide__slide .slide-content-wrapper').forEach(function (item) {
              var current_slide = item.querySelector('.splide__slide__container a');
              if (current_slide == image) {
                item_number = slideritems.length;
              }
              var targetHref = current_slide.getAttribute('href');
              var asset_url = item.querySelector('.splide__slide__container').getAttribute('asset-url');
              if (asset_url != null && asset_url != '') {
                targetHref = asset_url;
              }
              var title = '';
              var description = '';
              if (item.querySelector('.readmore-text') != null) {
                description = item.querySelector('.readmore-text').innerHTML;
              } else if (item.querySelector('p') != null) {
                description = item.querySelector('p').outerHTML;
              }
              if (item.querySelector('.details-box strong') != null) {
                title = item.querySelector('.details-box strong').outerHTML;
              }
              slideritems.push({
                'href': targetHref,
                'description': title + description
              });
            });
            lightbox.setElements(slideritems);
            lightbox.openAt(item_number);
          });
        });
        galleryField.classList.add('gallery-processed');
      });
    }
  };
})(Drupal);